http:
  port: 8080

apiEndpoints:
  stories:
    path: /api/*
    target: http://localhost:3000
    methods: GET, POST

serviceEndpoints:
  backend:
    url: http://localhost:3000

policies:
  - proxy

pipelines:
  default:
    apiEndpoints:
      - stories
    policies:
      - proxy:
          - action:
              serviceEndpoint: backend
              changeOrigin: true
